### ISSUE TITLE
People do bully

### ISSUE THREAD

**Issue by BlackStoneOfficial** [BlackStoneOfficial/UsergeBlack#3]
I don't like people bothering me by the name of this project. 

Please don't be racist-y to yourself.
Logic. Such good. Wow.

Bye.

**Comment by jazz667** [comment]
Thanks for your awesome contribution in userge black , I wish you luck and wish that your delete yourself as well

**Comment by BlackStoneOfficial** [comment]
> Thanks for your awesome contribution in userge black , I wish you luck and wish that you delete yourself as well along with your repo

Thanks for contributing so much! You got write access to this repository now.

Do what you want, I will send you my account credentials on Telegram!

The world is free, eat a bee.

**Comment by rojserbest** [comment]
lol

**Comment by rojserbest** [comment]
gitgram

**Comment by BlackStoneOfficial** [comment]
> gitgram

what gitgram

**Comment by Harsh-br0** [comment]
Hah

**Comment by jazz667** [comment]
> Hah

Owner abuse going here , deleting our comments 🥺

**Comment by rojserbest** [comment]
oh no

**Comment by Harsh-br0** [comment]
> Owner abuse going here , deleting our comments 🥺 , protect us chief
 
![](https://telegra.ph/file/7effa3a79cbc6f3ec63c1.jpg)

**Comment by Harsh-br0** [comment]
Previous issue was good to make it junk

**Comment by Veith-999** [comment]
# Aha

**Comment by TomyPrs** [comment]
Owo``

**Comment by rojserbest** [comment]
fuck
